### ISSUE TITLE
exception error: undefined function soap:wsdl2erlang/1

### ISSUE THREAD

**Issue by Natallia-Bahlai** [bet365/soap#11]
I am trying to run command:
`soap:wsdl2erlang("http://www.webservicex.net/CurrencyConvertor.asmx?WSDL").
`
and I am getting this error:
`** exception error: undefined function soap:wsdl2erlang/1`

**Comment by cmullaparthi** [comment]
Sorry for the delay in responding. Is the soap module in your code path?

``` erlang
code:get_path().
```

Will tell you what paths exist in your code path.
