### ISSUE TITLE
Odbc

### ISSUE THREAD

**Issue by edudemy** [bet365/soap#5]
Hi @cmullaparthi,

Is there a different repo for the odbc libraries open sourced according to this article on erlang-solutions. 

https://www.erlang-solutions.com/blog/improving-erlang-enterprise-tooling-an-open-source-initiative-by-bet365.html 

Regards,

**Comment by cmullaparthi** [comment]
Hi @edudemy,

The changes to the odbc library are ready but not released yet as we are testing it with our internal applications first. Hopefully should be released soon.

**Comment by zdeneksejcek** [comment]
Hi,

have you released ODBC already or still in development?

Thanks,
ZS.

**Comment by Startigers** [comment]
Hi,

is ODBC still in development or has your plan changed and bet365 won't release it?

Thanks,
Arne
